name: Build docs

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update gh-pages with docs
    steps:
      - name: Checkout Belvo Python SDK repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install requests
        run: pip install requests
      - name: Install all dependencies (pdoc + more)
        run: pip install pdoc
      - name: Build docs into docs/ folder
        run: pdoc ./belvo -o docs --docformat google
      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout file
#         uses: actions/checkout@v3
#       - name: Setup python
#         uses: actions/setup-python@v3
#       - name: Install all dependencies (pdoc + more)
#         run: pip install pdoc
#       - name: Build docs into docs/ folder
#         run: pdoc belvo -o docs/
#       - run: tar --directory docs/ -hcf artifact.tar .
#       - uses: actions/upload-artifact@v3
#         with:
#           name: github-pages
#           path: ./artifact.tar
  
#   # Deploy the artifact to GitHub pages.
#   # This is a separate job so that only actions/deploy-pages has the necessary permissions.
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     permissions:
#       pages: write
#       id-token: write
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     steps:
#       - id: deployment
#         uses: actions/deploy-pages@v1